server:
  port: 8080
  read_timeout: 15s
  write_timeout: 15s
  idle_timeout: 60s

routes:
  - path: "/api/v1/users"
    target: "http://localhost:3001"
  - path: "/api/v1/orders"
    target: "http://localhost:3002"
  - path: "/api/v1/products"
    target: "http://localhost:3003"

cors:
  allow_origins: ["*"]
  allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allow_headers: ["Content-Type", "Authorization"]